export const CAKE_ACTIONS_TYPES = {
  BUY_CAKES: "BUY_CAKES",
};
export const ICECREAM_ACTIONS_TYPES = {
  BUY_ICECREAM: "BUY_ICECREAM",
};

export const USER_ACTIONS_TYPES = {
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
};
